name: CI Maven Project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PORT: 8080
    strategy:
      matrix:
        java-version: [8, 11, 17]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Build tests in Maven
      run: mvn test
