# This is a basic workflow to help you get started with Actions

name: Generate from template

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    if: github.event.head_commit.message == 'Initial commit'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace variables in README
      run: sed -i 's/{{REPO_URL}}/${{ github.repository_owner }}\/${{ github.event.repository.name }}/g' README.md
   
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate README
        
    - name: Disable Workflow
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${{ github.run_id }}
        gh workflow disable 'Generate from template'
