# This is a basic workflow to help you get started with Actions

name: Test CI

# Controls when the workflow will run
on:
  workflow_run:
    workflows:
      - CI Maven Project
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Check if CI tests are running on Java 8 
        run: gh run view ${{ toJSON(github.event.workflow_run.id) }} --log | grep -q 'java.version = 1.8'
      
      - name: Check if CI tests are running on Java 11 
        run: gh run view ${{ toJSON(github.event.workflow_run.id) }} --log | grep -q 'java.version = 11'
        
      - name: Check if CI tests are running on Java 17 
        run: gh run view ${{ toJSON(github.event.workflow_run.id) }} --log | grep -q 'java.version = 17'
      
